In [5]:
import pandas as pd

In [ ]:
"""
tablas:
    Proyecto✅
        id_proyecto PK VARCHAR
        nombre_proyecto VARCHAR --> nombres de los 5 proyectos -> Proyecto_HLF, Proyecto_EDA, Proyecto_BBDD, Proyecto_ML, Proyecto_Deployment
        id_vertical FK VARCHAR
    Promocion✅
        id_promocion PK VARCHAR
        clase.Promocion y claustro.Promocion VARCHAR
        clase.Fecha_comienzo DATE
    Persona✅
        id_persona PK VARCHAR
        clase.Nombre y claustro.Nombre VARCHAR
        clase.Email VARCHAR (seria null para profesores)
        id.rol FK VARCHAR
    Campus✅
        id_campus PK VARCHAR
        clase.Campus y claustro.Campus VARCHAR
    Rol✅
        id_rol PK VARCHAR
        claustro.Rol VARCHAR
    Vertical✅
        id_vertical PK VARCHAR
        claustro.Vertical VARCHAR
    Modalidad✅
        id_modalidad PK VARCHAR
        claustro.Modalidad VARCHAR
    Edicion✅
        id_edicion PK VARCHAR
        id_campus FK VARCHAR
        id_promocion FK VARCHAR
        id_vertical FK VARCHAR
        id_modalidad FK VARCHAR
    Inscripcion✅
        id_inscripcion PK VARCHAR
        id_persona FK VARCHAR
        id_edicion FK VARCHAR
    Calificacion✅
        id_evaluacion PK VARCHAR
        resultado BOOL
        id_persona FK VARCHAR
        id_proyecto FK VARCHAR



MEJORAS:
    Poner Apto No Apto en Proyecto como bool
    Poner las FK como constraint
    Poner cuando hay muchos insert como union
    PK -> hash
    herencia persona -> alumno, profesor ?????????


atributos csv de las clases:
    ✅Nombre
    ✅Email
    ✅Promocion
    ✅Fecha_comienzo
    ✅Campus
    ✅Proyecto_HLF
    ✅Proyecto_EDA
    ✅Proyecto_BBDD
    ✅Proyecto_ML
    ✅Proyecto_Deployment

atributos csv claustro:
    ✅Nombre
    ✅Rol
    ✅Vertical
    ✅Promocion
    ✅Campus
    ✅Modalidad
"""

In [6]:
clase_1=pd.read_csv("clase_1.csv",sep=";")
clase_1

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
5,Leoncio Tena,Leoncio_Tena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
6,Odalys Torrijos,Odalys_Torrijos@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Eduardo Caparrós,Eduardo_Caparrós@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
8,Ignacio Goicoechea,Ignacio_Goicoechea@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
9,Clementina Santos,Clementina_Santos@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
10,Daniela Falcó,Daniela_Falcó@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
11,Abraham Vélez,Abraham_Vélez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano Menéndez,Maximiliano_Menéndez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
13,Anita Heredia,Anita_Heredia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Eli Casas,Eli_Casas@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [ ]:
#clase_1["Campus"].nunique()
clase_1["Nombre"].nunique()

15

In [7]:
clase_2=pd.read_csv("clase_2.csv",sep=";")
clase_2

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
1,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
2,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
3,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
4,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
5,Joaquina Asensio,Joaquina_Asensio@gmail.com,Febrero,12/02/2024,Madrid,No Apto,No Apto,Apto,Apto,Apto
6,Cristian Sarabia,Cristian_Sarabia@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,No Apto,Apto,Apto
7,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
8,Desiderio Jordá,Desiderio_Jordá@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,No Apto,Apto
9,Rosalina Llanos,Rosalina_Llanos@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto

In [8]:
clase_3=pd.read_csv("clase_3.csv",sep=";")
clase_3

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
5,Julie Ferrer,Julie_Ferrer@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia Cabañas,Mireia_Cabañas@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Flavia Amador,Flavia_Amador@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,Apto,Apto
8,Albino Macias,Albino_Macias@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
9,Ester Sánchez,Ester_Sánchez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,No Apto,Apto
10,Luis Miguel Galvez,Luis_Miguel_Galvez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
11,Loida Arellano,Loida_Arellano@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
12,Heraclio Duque,Heraclio_Duque@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto Figueras,Herberto_Figueras@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [9]:
clase_4=pd.read_csv("clase_4.csv",sep=";")
clase_4

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
1,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
2,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
3,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
4,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto
5,Ricarda Tovar,Ricarda_Tovar@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
6,Alejandra Vilaplana,Alejandra_Vilaplana@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
7,Daniel Rosselló,Daniel_Rosselló@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
8,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
9,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
10,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
11,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,No Apto,Apto
12,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto

In [11]:
claustro=pd.read_csv("claustro.csv",sep=";")
claustro

               Nombre Rol Vertical   Promocion    Campus   Modalidad
0           Noa Yáñez  TA       DS  Septiembre    Madrid  Presencial
1   Saturnina Benitez  TA       DS  Septiembre    Madrid  Presencial
2          Anna Feliu  TA       FS  Septiembre    Madrid  Presencial
3       Rosalva Ayuso  TA       FS  Septiembre  Valencia  Presencial
4    Ana Sofía Ferrer  TA       FS     Febrero  Valencia  Presencial
5     Angélica Corral  TA       FS     Febrero    Madrid  Presencial
6         Ariel Lledó  TA       DS  Septiembre    Madrid  Presencial
7         Mario Prats  LI       FS     Febrero  Valencia      Online
8   Luis Ángel Suárez  LI       FS  Septiembre    Madrid      Online
9  María Dolores Diaz  LI       DS  Septiembre    Madrid      Online

In [14]:
print(clase_1.isna().any().any())
print(clase_2.isna().any().any())
print(clase_3.isna().any().any())
print(clase_4.isna().any().any())
claustro.isna().any().any()

False
False
False
False

np.False_